/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "debug.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DebugRequest, DebugRequest, AUTO)


PB_BIND(DebugResponse, DebugResponse, AUTO)


PB_BIND(DebugVal, DebugVal, AUTO)


PB_BIND(DebugPeekRequest, DebugPeekRequest, AUTO)


PB_BIND(DebugPeekResponse, DebugPeekResponse, AUTO)


PB_BIND(DebugPokeRequest, DebugPokeRequest, AUTO)


PB_BIND(DebugPokeResponse, DebugPokeResponse, AUTO)


PB_BIND(DebugReadPrintBufRequest, DebugReadPrintBufRequest, AUTO)


PB_BIND(DebugReadPrintBufResponse, DebugReadPrintBufResponse, AUTO)


PB_BIND(DebugReadVarsRequest, DebugReadVarsRequest, AUTO)


PB_BIND(DebugReadVarsResponse, DebugReadVarsResponse, AUTO)


PB_BIND(DebugReadVarsResponse_Var, DebugReadVarsResponse_Var, AUTO)


PB_BIND(DebugWriteVarRequest, DebugWriteVarRequest, AUTO)


PB_BIND(DebugWriteVarResponse, DebugWriteVarResponse, AUTO)


PB_BIND(DebugTraceRequest, DebugTraceRequest, AUTO)


PB_BIND(DebugTraceResponse, DebugTraceResponse, AUTO)


PB_BIND(DebugTraceResponse_Sample, DebugTraceResponse_Sample, AUTO)






